### ISSUE TITLE
Explicitly define choice type column's implementation as a String

### ISSUE THREAD

**Issue by Haider8** [oscarine/oscarine-api#113]
https://github.com/oscarine/oscarine-api/blob/146c21535ad2b063335951f83433563d9def4fa7/app/db_models/item.py#L15

`sqlalchemy-utils docs:`

https://sqlalchemy-utils.readthedocs.io/en/latest/data_types.html#module-sqlalchemy_utils.types.choice

**Comment by ashrafmahmood** [comment]
This change is not required.
