### ISSUE TITLE
Email verification at the time of registration 

### ISSUE THREAD

**Issue by Haider8** [oscarine/oscarine-api#8]

**Comment by mohdamanzaidansari** [comment]
I would like to work around this issue. flask-mail will be used to send verification email containing jwt token to user.

**Comment by Haider8** [comment]
Okay, you can send the PR then, @iamareebjamal will take a look at it. Do we have to create a new route for sending emails?

**Comment by mohdamanzaidansari** [comment]
No we don't need a new route for sending email , but we need a verification
route to receive the token back from the user which was sent in the email.

**Comment by iamareebjamal** [comment]
Let's use a JWT token with a different scope to separate from auth tokens

**Comment by mohdamanzaidansari** [comment]
@iamareebjamal  i am working on this issue and it's almost working. but i wanna know what should be the response after successful verification of email.  should  it be a json message saying your email has been successfully confirmed.or some thing else.

**Comment by iamareebjamal** [comment]
```json
{
  "success": true,
  "message": "your email has been successfully confirmed"
}
```
